### ISSUE TITLE
spawning two entities with same Handle<EffectAsset> results in wgpu compute shader validation error

### ISSUE THREAD

**Issue by johnny-smitherson** [djeedai/bevy_hanabi#399]
**Crate versions**
`bevy` version: 0.14.2 
`bevy_hanabi` version:  0.13.0 + main commit acf80edf844a03aa04784fb147a80050448fc127

**Describe the bug**
Spawning two fireworks entities on the same `Handle<EffectAsset>` crashes the window with wgpu compute shader validation error.

**Expected behavior**
Two entities spawn with same effect, or some custom crate panic error message telling me not to do that.

**To Reproduce**
1. Go to fireworks example (also tried ribbon example)
2. Give the effect and the ribbons more capacity.
3. Spawn two fireworks entities on the same cloned `Handle<EffectAsset>`.
4. Crash
```diff
diff --git a/examples/firework.rs b/examples/firework.rs
index 3cc1f5b..451cedb 100644
--- a/examples/firework.rs
+++ b/examples/firework.rs
@@ -103,13 +103,13 @@ fn setup(mut commands: Commands, mut effects: ResMut<Assets<EffectAsset>>) {

     let effect = EffectAsset::new(
         // 2k lead particles, with 32 trail particles each
-        2048,
+        4*2048,
         Spawner::burst(2048.0.into(), 2.0.into()),
         writer.finish(),
     )
     // Tie together trail particles to make arcs. This way we don't need a lot of them, yet there's
     // a continuity between them.
-    .with_ribbons(2048 * 32, 1.0 / 64.0, 0.2, 0)
+    .with_ribbons(4*2048 * 32, 1.0 / 64.0, 0.2, 0)
     .with_name("firework")
     .init_groups(init_pos, lead)
     .init_groups(init_vel, lead)
@@ -150,9 +150,18 @@ fn setup(mut commands: Commands, mut effects: ResMut<Assets<EffectAsset>>) {
     commands.spawn((
         Name::new("firework"),
         ParticleEffectBundle {
-            effect: ParticleEffect::new(effect1),
+            effect: ParticleEffect::new(effect1.clone()),
             transform: Transform::IDENTITY,
             ..Default::default()
         },
     ));
+
+    commands.spawn((
+        Name::new("firework2"),
+        ParticleEffectBundle {
+            effect: ParticleEffect::new(effect1),
+            transform: Transform::from_translation(Vec3::X),
+            ..Default::default()
+        },
+    ));
 }

```

```diff
diff --git a/examples/ribbon.rs b/examples/ribbon.rs
index 31978fd..5ed0139 100644
--- a/examples/ribbon.rs
+++ b/examples/ribbon.rs
@@ -104,11 +104,19 @@ fn setup(mut commands: Commands, mut effects: ResMut<Assets<EffectAsset>>) {

     commands
         .spawn(ParticleEffectBundle {
-            effect: ParticleEffect::new(effect),
+            effect: ParticleEffect::new(effect.clone()),
             transform: Transform::IDENTITY,
             ..default()
         })
         .insert(Name::new("ribbon"));
+
+        commands
+        .spawn(ParticleEffectBundle {
+            effect: ParticleEffect::new(effect),
+            transform: Transform::from_translation(Vec3::X),
+            ..default()
+        })
+        .insert(Name::new("ribbon2"));
 }

 fn move_head(
```

**logs**

```
     Running `target\debug\examples\firework.exe`
2024-11-16T03:23:54.811628Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation    
2024-11-16T03:23:54.812521Z  WARN wgpu_hal::vulkan::instance: GENERAL [Loader Message (0x0)]
        windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
2024-11-16T03:23:54.812664Z  WARN wgpu_hal::vulkan::instance:   objects: (type: INSTANCE, hndl: 0x2252cee6f20, name: ?)
2024-11-16T03:23:54.827789Z  WARN wgpu_hal::dx12::instance: Unable to enable D3D12 debug interface: 0x887A002D    
2024-11-16T03:23:54.828100Z  WARN wgpu_hal::auxil::dxgi::factory: Unable to enable DXGI debug interface: 0x887A002D
2024-11-16T03:23:54.830071Z  WARN wgpu_hal::dx12::shader_compilation::dxc: Failed to load dxil.dll. Defaulting to FXC instead: Failed to load library "dxil.dll": LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }
2024-11-16T03:23:54.985732Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 3090", vendor: 4318, device: 8708, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.70", backend: Vulkan }    
2024-11-16T03:23:55.002228Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3090", vendor: 4318, device: 8708, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "560.70", backend: Vulkan }
2024-11-16T03:23:55.354929Z  INFO bevy_winit::system: Creating new window "🎆 Hanabi — firework" (Entity { index: 0, generation: 1 })
2024-11-16T03:23:55.683635Z  INFO naga::back::spv::writer: Skip function Some("get_camera_position_effect_space")    
2024-11-16T03:23:55.683884Z  INFO naga::back::spv::writer: Skip function Some("get_camera_rotation_effect_space")
2024-11-16T03:23:55.684095Z  INFO naga::back::spv::writer: Skip function Some("transform_position_simulation_to_clip")
2024-11-16T03:23:55.828201Z  INFO naga::back::spv::writer: Skip function Some("sample_input_3x3_tent")    
2024-11-16T03:23:55.845939Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread 'main' panicked at C:\Users\john\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.20.1\src\backend\wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In a ComputePass
      note: encoder = `<CommandBuffer-(3, 1, Vulkan)>`
    In a dispatch command, indirect:true
      note: compute pipeline = `hanabi:pipeline_init_compute`
    Indirect buffer uses bytes 128..140 which overruns indirect buffer of size 128

```

and same for ribbons

**question**

Is this unsupported? e.g. https://github.com/djeedai/bevy_hanabi/issues/73

While there is a mention of [it being supported](https://github.com/djeedai/bevy_hanabi/blob/f6e6a7942097023e55b63c6db838583fb2899d47/src/lib.rs#L154-L155), there is [no example or test that spawns two entities](https://github.com/search?q=repo%3Adjeedai%2Fbevy_hanabi%20commands.spawn&type=code) with the same asset handle.

But [it worked for this example](https://github.com/djeedai/bevy_hanabi/issues/321) when [it spawned 100 clones of an effect](https://github.com/jakkos-net/bevy_hanabi_64_issue/blob/9e0db4a1378275aac47fda37958193b9e2b36eec/src/main.rs#L127) using a previous version. 

The pattern you see a lot in bevy is that the `Handle<*Asset>` holds expensive things that can be re-used in many entities without recomputing them; is that not the case here?

Is the user supposed to create a new EffectAsset for each instantiation of an effect (e.g. each fireworks explosion that happens in parallel)? Wouldn't that compile and drop a lot of compute shaders with the exact same generated expressions?

**workaround**

Is there any known workaround for spawning lots and lots of fireworks? For avoiding churn, it seems like these EffectAssets could be kept in a user-managed pool, such that each Handle<EffectAsset> is only on one entity at a time. Is this a pattern that happens in your own projects, or do you just create a new EffectAsset for each effect instance?

**Comment by djeedai** [comment]
The `instancing.rs` example spawns tens of the same effect at once.
https://github.com/djeedai/bevy_hanabi/blob/f6e6a7942097023e55b63c6db838583fb2899d47/examples/instancing.rs#L86

This is a bug.

**Comment by djeedai** [comment]
I can't repro on macOS. I get 2 fireworks as expected and no error.

**Comment by djeedai** [comment]
To clarify, the asset and handle pattern _is_ the intended usage, like in Bevy. You create an `EffecfAsset`, either at runtime or by deserializing a previously created asset from file (ideally; although the asset format is not very stable nor comprehensive yet, so this workflow doesn't work well currently). And then at runtime you spawn as many effect instances as you want, referencing the same asset via its handle. Same as any other asset in Bevy.

**Comment by johnny-smitherson** [comment]
I see the "instancing" example now - it works on this machine, no error. 

I also tried updating nvidia drivers and windows update, no change.

I'll try to do it with linux on this same machine, to maybe see if it's windows-specific issue or nvidia-specific issue.

Let me know if there's some more debugging info I can provide

**Comment by djeedai** [comment]
I'll try on Windows when I get a chance. There are differences between platforms, notably in alignment of buffers, so it's quite possible it's a bug only on some. The drivers shouldn't matter much in that case but thanks for checkig anyway, this helps narrow down the issue.

**Comment by johnny-smitherson** [comment]
I was also curious why the "instancing" example works and the "fireworks" example doesn't. After trying a few things, it seems that the problem is having a second `ParticleGroupSet`. In both "fireworks" and "ribbons" examples, commenting out the ".with_ribbons(...)" line avoids the crash.

**Comment by johnny-smitherson** [comment]
Ok, tried out different configurations on desktop and a laptop with switchable intel+nvidia:

- Debian / Desktop Nvidia RTX 3090 = crash
- Debian / Laptop Nvidia GTX 1050 = crash
- Debian / Laptop Intel HD Graphics 630 = crash

I don't have windows on the laptop and don't have plans to install any

**Comment by djeedai** [comment]
The exact GPU or machine probably doesn't matter here. What matters I think is the graphics API and possibly the GPU series, which change the hardware limits that wgpu has to follow. Or there's a race condition. The error message basically says there's an out of bound buffer access.

**Comment by djeedai** [comment]
Ok I can repro on Windows with Vulkan.

**Comment by johnny-smitherson** [comment]
Graphics API as in VK vs. DirectX vs. GL ? I tried all 3 under windows, getting same error.

GL spews some extra warnings about Cube vs. CubeArray and D2 vs. D2Array, but it does anyway even when no crash.

I looked at the alignments for the buffers in the traces, that looks OK. Based on the buffer size and slice, I think it's complaining about this one:

**2 fireworks without .with_ribbons()**
```
2024-11-16T19:48:46.978315Z  WARN bevy_hanabi::render: YYY BufferTable { buffer: None, buffer_usage: BufferUsages(COPY_SRC | COPY_DST | STORAGE | INDIRECT), label: Some("hanabi:buffer:dispatch_indirect"), item_size: 16, aligned_size: 32, capacity: 0, active_count: 0, free_indices: [], pending_values: [], extra_pending_values: [] }
2024-11-16T19:48:46.978765Z  WARN bevy_hanabi::render: YYY BufferTable { buffer: None, buffer_usage: BufferUsages(COPY_SRC | COPY_DST | STORAGE | INDIRECT), label: Some("hanabi:buffer:dispatch_indirect"), item_size: 16, aligned_size: 32, capacity: 1, active_count: 1, free_indices: [], pending_values: [], extra_pending_values: [GpuDispatchIndirect { x: 0, y: 1, z: 1, pong: 0 }] }
2024-11-16T19:48:46.979135Z  WARN bevy_hanabi::render::buffer_table: reserve('#0:hanabi:buffer:dispatch_indirect'): increase capacity from 0 to 2 elements, old size 0 bytes, new size 64 bytes
```

**2 fireworks with `.with_ribbons()`**
```
2024-11-16T19:43:55.188925Z  WARN bevy_hanabi::render: Adding 2 newly spawned effects
2024-11-16T19:43:55.189167Z  WARN bevy_hanabi::render: YYY BufferTable { buffer: None, buffer_usage: BufferUsages(COPY_SRC | COPY_DST | STORAGE | INDIRECT), label: Some("hanabi:buffer:dispatch_indirect"), item_size: 16, aligned_size: 32, capacity: 0, active_count: 0, free_indices: [], pending_values: [], extra_pending_values: [] }
2024-11-16T19:43:55.189741Z  WARN bevy_hanabi::render: YYY BufferTable { buffer: None, buffer_usage: BufferUsages(COPY_SRC | COPY_DST | STORAGE | INDIRECT), label: Some("hanabi:buffer:dispatch_indirect"), item_size: 16, aligned_size: 32, capacity: 2, active_count: 2, free_indices: [], pending_values: [], extra_pending_values: [GpuDispatchIndirect { x: 0, y: 1, z: 1, pong: 0 }, GpuDispatchIndirect { x: 0, y: 1, z: 1, pong: 0 }] }
2024-11-16T19:43:55.190277Z  WARN bevy_hanabi::render::buffer_table: reserve('#0:hanabi:buffer:dispatch_indirect'): increase capacity from 0 to 4 elements, old size 0 bytes, new size 128 bytes
...
    Indirect buffer uses bytes 128..140 which overruns indirect buffer of size 128
```

**Comment by djeedai** [comment]
I have a fix.

**Comment by djeedai** [comment]
@johnny-smitherson can you please try again with latest `main`? I just pushed a fix. Thanks!

**Comment by johnny-smitherson** [comment]
<img width="833" alt="Screenshot 2024-11-17 003920" src="https://github.com/user-attachments/assets/0f540c47-df48-44a5-89f4-8b097f0a598e">

works great, thanks

**Comment by johnny-smitherson** [comment]
<img width="925" alt="Screenshot 2024-11-17 004726" src="https://github.com/user-attachments/assets/d6edc922-09dd-46a1-b806-ee2e4fe95db5">

this one too

**Comment by djeedai** [comment]
Released v0.13.1 with that fix. Thanks for reporting!

**Comment by ethereumdegen** [comment]
I am using 0.14 an i still get this crash 

```
2024-12-13T06:08:08.668231Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation    
2024-12-13T06:08:08.669727Z  WARN wgpu_hal::vulkan::instance: GENERAL [Loader Message (0x0)]
	terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /usr/lib/x86_64-linux-gnu/libvulkan_virtio.so. Skipping this driver.    
2024-12-13T06:08:08.669752Z  WARN wgpu_hal::vulkan::instance: 	objects: (type: INSTANCE, hndl: 0x60b21f860aa0, name: ?)    
2024-12-13T06:08:08.681640Z  WARN wgpu_hal::gles::egl: No config found!    
2024-12-13T06:08:08.681663Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively    
2024-12-13T06:08:08.722442Z  WARN wgpu_hal::gles::adapter: Max vertex attribute stride unknown. Assuming it is 2048    
thread 'Compute Task Pool (7)' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_hanabi-0.14.0/src/render/mod.rs:3687:13:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

``` 

is this different or the same ?

**Comment by djeedai** [comment]
Sounds bad, we shouldn't crash because of a missing component.
